### ISSUE TITLE
Autorenkennzeichnung in Artikeln

### ISSUE THREAD

**Issue by Agile-Usergroup-Kassel** [Agile-Usergroup-Kassel/blog#1]
Da hier (hoffentlich) mehrere Autoren schreiben werden, sollte jeder Artikel mit dem Namen des Autors enthalten.

* Konfiguration ändern
* oder: Herausfinden, wie das mit Markdown geht

**Comment by juengling** [comment]
Hier ist eine Idee zu finden, aber ich habe sie wohl noch nicht richtig eingebaut: https://gist.github.com/ravasthi/1834570

**Comment by Agile-Usergroup-Kassel** [comment]
Zweiter Versuch von https://blog.sorryapp.com/blogging-with-jekyll/2014/02/06/adding-authors-to-your-jekyll-site.html, funktioniert aber offenbar auch nicht.
